// Generated by gencpp from file first_package/nums.msg
// DO NOT EDIT!


#ifndef FIRST_PACKAGE_MESSAGE_NUMS_H
#define FIRST_PACKAGE_MESSAGE_NUMS_H

#include <ros/service_traits.h>


#include <first_package/numsRequest.h>
#include <first_package/numsResponse.h>


namespace first_package
{

struct nums
{

typedef numsRequest Request;
typedef numsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nums
} // namespace first_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::first_package::nums > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::first_package::nums&) { return value(); }
};

template<>
struct DataType< ::first_package::nums > {
  static const char* value()
  {
    return "first_package/nums";
  }

  static const char* value(const ::first_package::nums&) { return value(); }
};


// service_traits::MD5Sum< ::first_package::numsRequest> should match
// service_traits::MD5Sum< ::first_package::nums >
template<>
struct MD5Sum< ::first_package::numsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::first_package::nums >::value();
  }
  static const char* value(const ::first_package::numsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_package::numsRequest> should match
// service_traits::DataType< ::first_package::nums >
template<>
struct DataType< ::first_package::numsRequest>
{
  static const char* value()
  {
    return DataType< ::first_package::nums >::value();
  }
  static const char* value(const ::first_package::numsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::first_package::numsResponse> should match
// service_traits::MD5Sum< ::first_package::nums >
template<>
struct MD5Sum< ::first_package::numsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::first_package::nums >::value();
  }
  static const char* value(const ::first_package::numsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_package::numsResponse> should match
// service_traits::DataType< ::first_package::nums >
template<>
struct DataType< ::first_package::numsResponse>
{
  static const char* value()
  {
    return DataType< ::first_package::nums >::value();
  }
  static const char* value(const ::first_package::numsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIRST_PACKAGE_MESSAGE_NUMS_H
